### ISSUE TITLE
Migrate dependency management to Poetry

### ISSUE THREAD

**Issue by EandrewJones** [UMD-ARLIS/incubator-flagon-distill#24]
## Synopsis
As part of preparing Distill to become a proper PyPI repo, I have propose we transition to using [Poetry](https://python-poetry.org/) for dependency and packaging management.

Tutorial:
[https://mathspp.com/blog/how-to-create-a-python-package-in-2022](https://mathspp.com/blog/how-to-create-a-python-package-in-2022)

### Benefits:
- Single tool to handle dependency management (like venv), building, and publishing to PyPi
- Enforce uniform standards across the project; make it easy for contributors to follow those standards
- Well designed and supported tool (it's not going to become deprecated)
- Seems to be de facto nowadays for new Python projects

### Cons:
- Yet another tool for users to learn (albeit easy IMO)

### Proposal:
To get started with Poetry, we need to 1) add poetry; 2) migrate existing dependencies and setup to a `pyproject.toml`

### Questions:
- What versions of python do we need to support?

@amirmghaemi @Jyyjy @poorejc

**Comment by Jyyjy** [comment]
Currently Distill requires Python 3.8 or later. This setup script has more details that may be helpful, although I've never been able to use it without errors. 

https://github.com/UMD-ARLIS/incubator-flagon-distill/blob/master/setup.py
